#!/usr/bin/env node
// Installs a global `yoink` command so an existing install can be updated or
// removed with `yoink update` / `yoink uninstall` instead of re-typing the
// curl install line or remembering `npm run helper:uninstall`. Re-run any
// time (remote-install.sh does this on every run) to re-bake the current
// repo path/branch into the wrapper, so it stays correct even if YOINK_DEST
// or YOINK_BRANCH differ from a previous install.
import { accessSync, constants } from 'node:fs'
import { chmod, lstat, mkdir, readlink, symlink, unlink, writeFile, appendFile, readFile } from 'node:fs/promises'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const run = promisify(execFile)

if (process.platform !== 'darwin') throw new Error('The Yoink CLI installer currently supports macOS only.')

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const appRoot = join(homedir(), 'Library', 'Application Support', 'Yoink')
const binDir = join(appRoot, 'bin')
const cliPath = join(binDir, 'yoink')

async function currentBranch() {
  try {
    const { stdout } = await run('git', ['-C', root, 'rev-parse', '--abbrev-ref', 'HEAD'])
    const branch = stdout.trim()
    return branch && branch !== 'HEAD' ? branch : 'main'
  } catch {
    return 'main'
  }
}

function shellQuote(value) {
  return `'${value.replaceAll("'", `'\\''`)}'`
}

const branch = await currentBranch()

const script = `#!/bin/sh
# Generated by scripts/install-cli.mjs \u2014 re-run that script (or
# scripts/remote-install.sh, which calls it) to regenerate this file.
set -eu
ROOT=${shellQuote(root)}
BRANCH=${shellQuote(branch)}

usage() {
  echo "Usage: yoink update | yoink uninstall" >&2
  exit 1
}

case "\${1:-}" in
  update)
    YOINK_DEST="\$ROOT" YOINK_BRANCH="\$BRANCH" \\
      curl -fsSL "https://raw.githubusercontent.com/OwaisQuadri/yoink/\$BRANCH/scripts/remote-install.sh" | sh
    ;;
  uninstall)
    ( cd "\$ROOT" && npm run helper:uninstall )
    node "\$ROOT/scripts/uninstall-cli.mjs"
    echo ""
    echo "Yoink uninstalled. Two things this did not touch:"
    echo "  - Remove the extension itself from chrome://extensions."
    echo "  - The cloned project at \$ROOT (delete it yourself if you want it gone)."
    ;;
  *)
    usage
    ;;
esac
`

await mkdir(binDir, { recursive: true, mode: 0o700 })
await writeFile(cliPath, script, { mode: 0o700 })
await chmod(cliPath, 0o700)

// Candidate directories to expose `yoink` on $PATH, most- to least-preferred.
// The first one that already exists and is writable wins; we never create
// /opt/homebrew/bin or /usr/local/bin ourselves (that's Homebrew's/macOS's
// job) but will create a personal ~/.local/bin as a last resort.
const candidates = [
  '/opt/homebrew/bin',
  '/usr/local/bin',
  join(homedir(), '.local', 'bin'),
]

async function isWritableDir(dir) {
  try {
    accessSync(dir, constants.W_OK)
    return true
  } catch {
    return false
  }
}

async function linkedToUs(linkPath) {
  try {
    const stat = await lstat(linkPath)
    if (!stat.isSymbolicLink()) return false
    return (await readlink(linkPath)) === cliPath
  } catch {
    return false
  }
}

let linked
for (const dir of candidates) {
  const target = join(dir, 'yoink')
  const isLast = dir === candidates.at(-1)
  if (isLast) await mkdir(dir, { recursive: true, mode: 0o755 })
  if (!(await isWritableDir(dir))) continue
  try {
    const exists = await lstat(target).then(() => true, () => false)
    if (exists && !(await linkedToUs(target))) {
      // Something else owns this path (a real file, or someone else's
      // `yoink`) \u2014 don't clobber it, try the next candidate.
      continue
    }
    if (exists) await unlink(target)
    await symlink(cliPath, target)
    linked = { dir, target }
    break
  } catch {
    continue
  }
}

if (linked && linked.dir === join(homedir(), '.local', 'bin')) {
  // $SHELL reflects the user's login shell, which is what a "new terminal"
  // actually launches — zsh has been the macOS default since Catalina, but
  // don't assume it for someone who switched to bash or fish.
  const shell = process.env.SHELL ?? ''
  const isFish = shell.endsWith('fish')
  const isBash = shell.endsWith('bash')
  const rcPath = isFish
    ? join(homedir(), '.config', 'fish', 'config.fish')
    : join(homedir(), isBash ? '.bash_profile' : '.zshrc')
  const pathLine = isFish
    ? 'fish_add_path $HOME/.local/bin'
    : 'export PATH="$HOME/.local/bin:$PATH"'
  await mkdir(dirname(rcPath), { recursive: true })
  const existing = await readFile(rcPath, 'utf8').catch(() => '')
  if (!existing.includes(pathLine)) {
    await appendFile(rcPath, `\n# Added by Yoink's installer so \`yoink\` is on PATH.\n${pathLine}\n`)
    process.stdout.write(`Added ~/.local/bin to PATH in ${rcPath}. Restart your terminal (or run: source ${rcPath}).\n`)
  }
}

if (linked) {
  process.stdout.write(`\`yoink\` command installed at ${linked.target} -> ${cliPath}\n`)
  process.stdout.write('Run `yoink update` or `yoink uninstall` any time.\n')
} else {
  // Shouldn't normally happen — ~/.local/bin is created and checked as the
  // last resort above — but something odd about this machine's
  // permissions (or a real, unrelated file already sitting at every
  // candidate path) means none of them could be used.
  process.stdout.write([
    'Could not find a writable directory on PATH to install the `yoink` command.',
    `The command itself is at: ${cliPath}`,
    'Link it yourself once you\'ve picked a directory on your PATH, e.g.:',
    `  ln -sf ${cliPath} ~/.local/bin/yoink`,
  ].join('\n') + '\n')
}
